### ISSUE TITLE
New controller + PowerTag module support

### ISSUE THREAD

**Issue by PMPoulsen** [Breina/PowerTagGateway#1]
It seems as there are several lines of PowerTag
It would be great if this integration can support the EER31800 (se.com/dk/da/product/EER31800/wiser-energy-ipmodul/) as this is the cheapest way to get the powerTag's integrated. The ModBus controller are quite expensive compared with this one.

I do understand that it may use a different communication API than ModBus so it may not be possible.

My original hope was to get the actual powertag included through ZigBee however this seems very difficult as well.
And adding the modules R9M22 Energisensor Resi PowerTag 1PN, R9M41 Energisensor Resi PowerTag 3PN, R9M42 Energisensor Resi PowerTag 3PN, (and probably more) would also be needed if the EER31800 can be integrate

**Comment by Breina** [comment]
I tried this first. Actually I have hardware laying around even.

The only way to get data out of the ER31800 is through Wiser Clou (https://community.se.com/t5/Schneider-Electric-Wiser-Forum/Wiser-Energy-SOAP-communication/m-p/377340/highlight/true#M9). I created a DHCP server in order to feed the device a custom DNS server in order to make it communicate with me, instead of the cloud. Turns out it only accepts SSL connections signed with the official Schneider CA, not my own. They locked their shit down properly.

The only way to communicate with Wiser Energy is [through its $15/month API](https://exchange.se.com/devportal/api/wiser-energy-api). If anyone is up to that, feel free to submit a PR, but I'm not doing it.

I would suggest changing your PowerTag module if you need it integrated. The tags themselves aren't even compatible either.

**Comment by PMPoulsen** [comment]
Thanks for your feedback.

I guess I had the feeling this might be the case. Fully understand that you are not integrating here. 

I do already have the tag installed and have the app, but as you describe this is a closed system.
So my only hope is if somebody figured out how to cennect through zigbee. It is too costly to change the 15 tags I have installed.

**Comment by Breina** [comment]
F
