### ISSUE TITLE
electricity consumption is not visible

### ISSUE THREAD

**Issue by hocine69** [Breina/PowerTagGateway#8]
Hi, 
I have an installation with 1 powertaglink A9XMDW20 and 8 powertag A9MEM1560. i find my product but i don't have all information.
As you can see, i don't have metering option. 
thx for your help.

I have the last version of powertaglink  Firmware Revision: 002.002.002
and the last version of HA

![Capture d’écran 2023-07-29 174241](https://github.com/Breina/PowerTagGateway/assets/140238039/e9e3ee62-a8b2-40ab-a48e-514f6b95edba)

**Comment by Breina** [comment]
I see that you're missing the gateway status, and all sensors. The integration seems to just have crashed during the loading of the sensors (after the binary_sensor and button are ready).

Can you please check the logs to check what exactly went wrong?

**Comment by hocine69** [comment]
[home-assistant_powertag_gateway_2023-07-30T13-56-17.860Z.log](https://github.com/Breina/PowerTagGateway/files/12209362/home-assistant_powertag_gateway_2023-07-30T13-56-17.860Z.log)

**Comment by Breina** [comment]
Please update to v0.1.4 and check if your issue is resolved.

Going off the spec, at least one of your entities is returning an `Invalid Value` for its Phase Sequence. So this version will be able to handle this. Consider setting that one up in your PowerTag Link's GUI, so that this integration can add phase specific entities as well.
